(* generated by dune *)

(** @canonical Netir.Ast *)
module Ast = Netir__Ast

(** @canonical Netir.Astmapper *)
module Astmapper = Netir__Astmapper

(** @canonical Netir.Nometa *)
module Nometa = Netir__Nometa

(** @canonical Netir.Prettyprint *)
module Prettyprint = Netir__Prettyprint
