lib: [
  "_build/install/default/lib/pirc/META"
  "_build/install/default/lib/pirc/dune-package"
  "_build/install/default/lib/pirc/metainfo/meta.ml" {"metainfo/meta.ml"}
  "_build/install/default/lib/pirc/metainfo/metainfo.a" {"metainfo/metainfo.a"}
  "_build/install/default/lib/pirc/metainfo/metainfo.cma" {"metainfo/metainfo.cma"}
  "_build/install/default/lib/pirc/metainfo/metainfo.cmi" {"metainfo/metainfo.cmi"}
  "_build/install/default/lib/pirc/metainfo/metainfo.cmt" {"metainfo/metainfo.cmt"}
  "_build/install/default/lib/pirc/metainfo/metainfo.cmx" {"metainfo/metainfo.cmx"}
  "_build/install/default/lib/pirc/metainfo/metainfo.cmxa" {"metainfo/metainfo.cmxa"}
  "_build/install/default/lib/pirc/metainfo/metainfo.ml" {"metainfo/metainfo.ml"}
  "_build/install/default/lib/pirc/metainfo/metainfo__Meta.cmi" {"metainfo/metainfo__Meta.cmi"}
  "_build/install/default/lib/pirc/metainfo/metainfo__Meta.cmt" {"metainfo/metainfo__Meta.cmt"}
  "_build/install/default/lib/pirc/metainfo/metainfo__Meta.cmx" {"metainfo/metainfo__Meta.cmx"}
  "_build/install/default/lib/pirc/netir/ast.ml" {"netir/ast.ml"}
  "_build/install/default/lib/pirc/netir/ast.mli" {"netir/ast.mli"}
  "_build/install/default/lib/pirc/netir/astmapper.ml" {"netir/astmapper.ml"}
  "_build/install/default/lib/pirc/netir/netir.a" {"netir/netir.a"}
  "_build/install/default/lib/pirc/netir/netir.cma" {"netir/netir.cma"}
  "_build/install/default/lib/pirc/netir/netir.cmi" {"netir/netir.cmi"}
  "_build/install/default/lib/pirc/netir/netir.cmt" {"netir/netir.cmt"}
  "_build/install/default/lib/pirc/netir/netir.cmx" {"netir/netir.cmx"}
  "_build/install/default/lib/pirc/netir/netir.cmxa" {"netir/netir.cmxa"}
  "_build/install/default/lib/pirc/netir/netir.ml" {"netir/netir.ml"}
  "_build/install/default/lib/pirc/netir/netir__Ast.cmi" {"netir/netir__Ast.cmi"}
  "_build/install/default/lib/pirc/netir/netir__Ast.cmt" {"netir/netir__Ast.cmt"}
  "_build/install/default/lib/pirc/netir/netir__Ast.cmti" {"netir/netir__Ast.cmti"}
  "_build/install/default/lib/pirc/netir/netir__Ast.cmx" {"netir/netir__Ast.cmx"}
  "_build/install/default/lib/pirc/netir/netir__Astmapper.cmi" {"netir/netir__Astmapper.cmi"}
  "_build/install/default/lib/pirc/netir/netir__Astmapper.cmt" {"netir/netir__Astmapper.cmt"}
  "_build/install/default/lib/pirc/netir/netir__Astmapper.cmx" {"netir/netir__Astmapper.cmx"}
  "_build/install/default/lib/pirc/netir/netir__Nometa.cmi" {"netir/netir__Nometa.cmi"}
  "_build/install/default/lib/pirc/netir/netir__Nometa.cmt" {"netir/netir__Nometa.cmt"}
  "_build/install/default/lib/pirc/netir/netir__Nometa.cmx" {"netir/netir__Nometa.cmx"}
  "_build/install/default/lib/pirc/netir/netir__Prettyprint.cmi" {"netir/netir__Prettyprint.cmi"}
  "_build/install/default/lib/pirc/netir/netir__Prettyprint.cmt" {"netir/netir__Prettyprint.cmt"}
  "_build/install/default/lib/pirc/netir/netir__Prettyprint.cmti" {"netir/netir__Prettyprint.cmti"}
  "_build/install/default/lib/pirc/netir/netir__Prettyprint.cmx" {"netir/netir__Prettyprint.cmx"}
  "_build/install/default/lib/pirc/netir/nometa.ml" {"netir/nometa.ml"}
  "_build/install/default/lib/pirc/netir/prettyprint.ml" {"netir/prettyprint.ml"}
  "_build/install/default/lib/pirc/netir/prettyprint.mli" {"netir/prettyprint.mli"}
  "_build/install/default/lib/pirc/opam"
]
libexec: [
  "_build/install/default/lib/pirc/metainfo/metainfo.cmxs" {"metainfo/metainfo.cmxs"}
  "_build/install/default/lib/pirc/netir/netir.cmxs" {"netir/netir.cmxs"}
]
doc: [
  "_build/install/default/doc/pirc/README.md"
]
