name: build-site

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - 'zola-site'
  pull_request:
    branches:
      - 'zola-site'

permissions:
  contents: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Zola Deploy to Pages
        uses: shalzz/zola-deploy-action@v0.23.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_ONLY: ${{ github.event_name == 'pull_request' }} #this prevents pull requests from triggering an update to the live site